import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          🍕 Welcome to Epic Pizza Reviews
        </h1>
        {data.map(x => (
          <p className={styles.description}>
          <b>{x.title}</b>: {x.content["6348025765512"].value} stars!
        </p>
        ))}
      </main>

    </div>
  )
}

export async function getStaticProps(){
  let data = (await fetch('https://berowra.sampoder.deta.app/api/collection/vpem6w9xh73r?content').then(r => r.json())).items
  return {props: {data}, revalidate: 30}
}